//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casino322.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public int Game_Id { get; set; }
        public System.DateTime Game_Date { get; set; }
        public string Game_Stavka { get; set; }
        public string Game_Result { get; set; }
        public int Game_Bet { get; set; }
        public string Win { get; set; }
        public int User_Id { get; set; }
        public int Win_Count { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
