//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casino322.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int Payment_Id { get; set; }
        public string TypePay { get; set; }
        public string MethodPay { get; set; }
        public int User_Id { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
