//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casino322.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int Session_Id { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime Session_End { get; set; }
        public int User_Id { get; set; }
        public int Games_Count { get; set; }
        public int Winnig_Count { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
